[project]
name = "remarks-server"
version = "0.1.0"
description = ""
authors = [{ name = "Laura Brekelmans", email = "mail@laura.fm" }]
readme = "README.md"
dependencies = ["Flask >= 3.0.3", "remarks @ ../../"]

[project.scripts]
remarks-server = "remarks_server.server:main"